# Generated by Django 4.1.1 on 2022-09-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-01-23'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
